name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        gradle-version: ["6-jdk8", "6-jdk11", "7-jdk8", "7-jdk11", "7-jdk17"]
    runs-on: ubuntu-latest
    container: gradle:${{ matrix.gradle-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Print Java and Gradle information
        run: |
          java -version
          gradle --version
      - name: Build package
        run: gradle build
      - name: Run unit tests
        run: gradle test
