name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        gradle-version: ["6-jdk8", "7-jdk8"]
    runs-on: ubuntu-latest
    container: gradle:${{ matrix.gradle-version }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          java -version
          gradle --version
      - run: gradle build
      - run: gradle test
